---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# rfinstats

<!-- badges: start -->
<!-- badges: end -->

This package contains some data sets from finnish statistial institute.

## Installation

You can install the development version of rfinstats from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("StranMax/rfinstats")
```

```{r example, message=FALSE, warning=FALSE}
library(rfinstats)
library(dplyr)
library(sf)
library(ggplot2)
```

```{r}
head(taantuvat)
```

```{r}
taantuvat_sf <- left_join(taantuvat, kunnat) |> st_as_sf()
```


```{r}
ggplot() +
  geom_sf(data = taantuvat_sf, aes(fill = luokka)) +
  theme_void()
```

```{r}
aluejaot_sf <- left_join(aluejaot, kunnat) |> st_as_sf()
```

```{r}
aluejaot_sf |>
  group_by(Maakunta) |>
  summarise(n = n(), do_union = TRUE) |>
  ggplot() +
  geom_sf(aes(fill = Maakunta), show.legend = FALSE) +
  theme_void()
```

